name: Dapper
favicon: null
layout_spectrum: 0.17968502920120955
typography_spectrum: 0.3245830114465207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9122657051775604
  lightness: 0.8533371926750988
  saturation: 0.19948170566931367
  rhythmicContrast: 0.3021586509421468
purpose: []
